version: '3.5'
services:
  event-collector:
    image: dcim-event-collector:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dcim-event-collector
    restart: always
    environment:
      - REDIS_IP=${REDIS_IP}
      - REDIS_PORT=${REDIS_PORT}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

